### ISSUE TITLE
[meta] Boost repository

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_xodr#13]
### Summary

This repository originally was thought to provide some plain XODR resources. Nowadays, this has evolved to provide some scripts for generating maps based on input arguments. Also it provides some GeoJSON information of the crosswalks.

### Proposal

 - [ ] Create a colcon package
 - [ ] Hide the empy scripts behind applications that are installable
 - [ ] Provide testing: At least smoke tests to know that they script are working correctly
 - [ ] Add GH Action CI.
