### ISSUE TITLE
Map Request: Split 12_map_integration into four sets of maps based on type and with extended approach / exit

### ISSUE THREAD

**Issue by liangfok** [maliput/maliput_xodr#46]
Currently, https://github.com/maliput/maliput_xodr/tree/main/standalone/12_map_integration contains four types of maps:

1. [x] straight road no crosswalk #57 
2. [x] straight road with crosswalk #58 
3. [x] intersection no crosswalk #59
4. [x] intersection with crosswalk #60 

We want to split this map into four sets of maps based on the above-list. Each set will have sub-maps that differ in lane width in the same manner as before (3m, 3.5m, 4m).

The names of the maps should also match the list above, e.g., use "straight_road_no_crosswalk" instead of "straight_forward."

The approach & exit of all maps should be 300m.

**Comment by francocipollone** [comment]
> The names of the maps should also match the list above, e.g., use "straight_road_no_crosswalk" instead of "straightforward."

At first I thought that the four maps were going to be in the same xodr (each xodr was going to vary in lane width) however this comment made me think each xodr should only contains the variation in lane width of one type of map. Right?

Please @liangfok review the following:

So to summarize, the output of this request will be:

- An xodr/geojson file with:
  - `straight road no crosswalk` with 3m lane width
  - `straight road no crosswalk` with 3.5m lane width
  - `straight road no crosswalk` with 4m lane width
  
- An xodr/geojson file with:
  - `straight road with crosswalk` with 3m lane width
  - `straight road with crosswalk` with 3.5m lane width
  - `straight road with crosswalk` with 4m lane width
  
- An xodr/geojson file with:
  - `intersection no crosswalk` with 3m lane width
  - `intersection no crosswalk` with 3.5m lane width
  - `intersection no crosswalk` with 4m lane width
  
- An xodr/geojson file with:
  - `intersection with crosswalk` with 3m lane width
  - `intersection with crosswalk` with 3.5m lane width
  - `intersection with crosswalk` with 4m lane width
  

Requirements for all the submaps:
 - The approach & exit of all maps should be 300m.
 - The submaps in each xodr file should be unconnected from other submaps

**Comment by liangfok** [comment]
Yes, that is correct. Each xodr should contain one map type, but with several variations in lane width for that particular type. Sorry for being confusing!

**Comment by liangfok** [comment]
Here's some additional context. We initially thought were were going to do large scenario variation sweeps across map types (maps with and without crosswalks, and with and without intersections). However, this ended up not being the case. We currently only do variation sweeps across a single map type, but with multiple lane widths. This is why our current request is to have each .xodr focus on a single map type, but with varying lane widths.

In the future, if we do need to perform scenario variation sweeps across map types, we will need to combine them into a single map. This is because our downstream testing infrastructure currently requires that all variations within a sweep set use the same map. Our scenario sweep infrastructure doesn't allow the map itself to be a sweep variation parameter.

I hope the above makes sense.

**Comment by francocipollone** [comment]
One small question @liangfok . There is no comments about stoplines. Are they necessary when crosswalk are required?

**Comment by liangfok** [comment]
No, not all crosswalks have stop lines. For these maps, the crosswalks have no stop lines.

**Comment by francocipollone** [comment]
Close as completed
